settings:
  title: 'Status Page'
  url: 'https://status.vcns.tech' # used for Slack messages
  logo: logo.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Healthy'
  notAllmonitorsOperational: 'Not Healthy'
  monitorLabelOperational: 'UP'
  monitorLabelNotOperational: 'DOWN'
  monitorLabelNoData: 'N/A'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'UP'
  dayInHistogramNotOperational: ' DOWN EVENTS' # xx incident(s) recorded

monitors:
  - id: vcns.tech # unique identifier
    name: vcns.tech
    description: 'Our homepage' # default=empty
    url: 'https://vcns.tech/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: shop.vcns.tech # unique identifier
    name: shop.vcns.tech
    description: 'Our shop' # default=empty
    url: 'https://shop.vcns.tech/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=true
    linkable: false # allows the title to be a link, default=true

  - id: 1778.3cx.cloud # unique identifier
    name: 3cx.cloud
    description: 'Our phone system and chat facility' # default=empty
    url: 'https://1778.3cx.cloud/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=true
    linkable: false # allows the title to be a link, default=true